// إعداد روابط الإحالة في دبّرها
// لا نضع أي رابط إحالة غير معتمد. الروابط الموجودة في links هي روابط شريك معتمدة.
window.DABBIRHA_AFFILIATE={
  amazon:{enabled:true,name:'أمازون',tag:'dabbirha-21',search:'https://www.amazon.sa/gp/search?tag=dabbirha-21&url=search-alias%3Daps&field-keywords='},
  noon:{
    enabled:true,
    name:'نون',
    url:'https://www.noon.com/saudi-ar/',
    links:{
      'Xiaomi Redmi Note 14':'https://s.noon.com/DlPsJs69Auk','Samsung Galaxy A26 5G':'https://s.noon.com/gKinfuKUgLw','Samsung Galaxy A36 5G':'https://s.noon.com/tZ1olod7lHY','Lenovo IdeaPad 1':'https://s.noon.com/ZjwADSOoJug','HP 15':'https://s.noon.com/73u7Y2_YbvQ','Lenovo IdeaPad Slim 3':'https://s.noon.com/xgMdRw0Umy8','ASUS Vivobook 15':'https://s.noon.com/ic0Knt8DuvU','Samsung 24 بوصة':'https://s.noon.com/p2tQALN_VBY','Samsung 32 بوصة':'https://s.noon.com/l2Cyl2RkQdw','LG UltraGear 27':'https://s.noon.com/CaueD21c6qI','Samsung Galaxy Buds FE':'https://s.noon.com/QCoC6_-cr28','Anker Soundcore':'https://s.noon.com/lt1Vb4jtZZQ','Sony WH-CH520':'https://s.noon.com/g8XqKRSX684','Sony WH-1000XM5':'https://s.noon.com/8dlC8stL1e8','HONOR 400 5G':'https://s.noon.com/WUAWZioMfTo','iPhone 16e':'https://s.noon.com/OwuVifEEtCU'
    },
    publicLinks:{
      'Samsung Galaxy A17 4G':'https://www.noon.com/saudi-ar/galaxy-a17-dual-sim-4g-black-4gb-ram-128gb-middle-east-version/N70214276V/p/','Samsung Galaxy A56 5G':'https://www.noon.com/saudi-ar/galaxy-a56-5g-dual-sim-awesome-graphite-8gb-ram-256gb-middle-east-version/N70158930V/p/','Samsung Galaxy S26 256GB':'https://supermall.noon.com/saudi-en/galaxy-s26-dual-sim-white-12gb-ram-256gb-5g-middle-east-version/N70283841V/p/','Samsung Galaxy S26 Ultra 256GB':'https://supermall.noon.com/saudi-en/galaxy-s26-ultra-dual-sim-black-12gb-ram-256gb-5g-middle-east-version/N70283855V/p/','Samsung Galaxy S26 Ultra 5G 256GB':'https://supermall.noon.com/saudi-en/galaxy-s26-ultra-dual-sim-black-12gb-ram-256gb-5g-middle-east-version/N70283855V/p/','Samsung Galaxy S25 Ultra 256GB':'https://supermall.noon.com/saudi-en/galaxy-s25-ultra-ai-dual-sim-titanium-grey-12gb-ram-256gb-middle-east-version/N70140492V/p/','Samsung Galaxy S25 Ultra 5G 256GB':'https://supermall.noon.com/saudi-en/galaxy-s25-ultra-ai-dual-sim-titanium-grey-12gb-ram-256gb-middle-east-version/N70140492V/p/','Samsung Galaxy A57 5G 256GB':'https://supermall.noon.com/saudi-ar/ts-ae-en-samsung-galaxy-a57/','Samsung Galaxy A57 5G 8GB 256GB':'https://supermall.noon.com/saudi-ar/ts-ae-en-samsung-galaxy-a57/','Samsung Galaxy A36 5G 6GB 128GB':'https://www.noon.com/saudi-ar/galaxy-a36-5g-dual-sim-awesome-black-6gb-ram-128gb-middle-east-version/N70165213V/p/','Samsung Galaxy Tab A11 64GB':'https://supermall.noon.com/saudi-ar/electronics-and-mobiles/digital_home/samsung/?isCarouselView=false&limit=50&sort%5Bby%5D=popularity&sort%5Bdir%5D=desc','Samsung 45W USB-C Charger':'https://supermall.noon.com/saudi-ar/electronics-and-mobiles/digital_home/samsung/?isCarouselView=false&limit=50&sort%5Bby%5D=popularity&sort%5Bdir%5D=desc','MacBook Neo A18 Pro 8GB 256GB':'https://www.noon.com/saudi-ar/macbook-neo-13-inch-display-a18-pro-6-core-cpu-5-core-gpu-16-core-neural-engine-processor-8gb-ram-256gb-ssd-english-and-arabic-keyboard-english-arabic-indigo/N70305948V/p/','JBL Tune 770NC':'https://supermall.noon.com/saudi-ar/tune-770nc-wireless-over-ear-headphones-blue/N70031887V/p/','Apple EarPods USB-C':'https://supermall.noon.com/saudi-en/earpods-with-usb-c-white/N53437242A/p/'
    }
  },
  temu:{enabled:false,name:'Temu',url:'https://www.temu.com/'},shein:{enabled:false,name:'SHEIN',url:'https://ar.shein.com/'},aliexpress:{enabled:false,name:'AliExpress',url:'https://www.aliexpress.com/'}
};
window.dabbarhaAffiliateClick=function(store,product){try{const key='dab_affiliate_clicks';const data=JSON.parse(localStorage.getItem(key)||'{}');data[store]=(data[store]||0)+1;localStorage.setItem(key,JSON.stringify(data));const pk='dab_affiliate_product_clicks';const products=JSON.parse(localStorage.getItem(pk)||'{}');const productKey=store+'|'+(product||'منتج غير محدد');products[productKey]=(products[productKey]||0)+1;localStorage.setItem(pk,JSON.stringify(products));localStorage.setItem('dab_last_affiliate',JSON.stringify({store,product:product||'',at:Date.now()}))}catch(e){}};
window.dabbarhaAffiliateUrl=function(store,product){const a=window.DABBIRHA_AFFILIATE&&window.DABBIRHA_AFFILIATE[store];if(!a||!a.enabled)return null;if(store==='amazon')return a.search+encodeURIComponent(product||'');if(store==='noon')return(a.links&&a.links[product])||(a.publicLinks&&a.publicLinks[product])||('https://www.noon.com/saudi-ar/search?q='+encodeURIComponent(product||''));return a.url||null};
window.dabbarhaIsAffiliateLink=function(store,product){const a=window.DABBIRHA_AFFILIATE&&window.DABBIRHA_AFFILIATE[store];if(!a||!a.enabled)return false;if(store==='amazon')return true;return!!(a.links&&a.links[product])};
