window.DABBIRHA_PRODUCTS=[
{name:'Samsung Galaxy A17 4G',category:'phone',price:719,rating:4.4,tags:'اقتصادي بطارية دراسة يومي',useCases:'دراسة استخدام يومي بطارية'},
{name:'Samsung Galaxy A26 5G',category:'phone',price:999,rating:4.4,tags:'5G بطارية قيمة',useCases:'يومي بطارية تواصل'},
{name:'Samsung Galaxy A36 5G',category:'phone',price:1073,rating:4.5,tags:'5G أداء شاشة بطارية',useCases:'أداء يومي ألعاب خفيفة'},
{name:'Samsung Galaxy A56 5G',category:'phone',price:1399,rating:4.5,tags:'5G أداء كاميرا بطارية',useCases:'تصوير ألعاب استخدام يومي'},
{name:'Xiaomi Redmi Note 14',category:'phone',price:775,rating:4.3,tags:'اقتصادي بطارية شاشة قيمة',useCases:'دراسة يومي بطارية'},
{name:'Xiaomi Redmi Note 14 Pro',category:'phone',price:1099,rating:4.4,tags:'أداء كاميرا شاشة بطارية',useCases:'تصوير ألعاب يومي'},
{name:'HONOR 400 5G',category:'phone',price:1409,rating:4.5,tags:'كاميرا 5G شاشة بطارية',useCases:'تصوير يومي'},
{name:'OnePlus Nord CE 4 Lite',category:'phone',price:799,rating:4.3,tags:'اقتصادي بطارية سريع',useCases:'بطارية يومي'},
{name:'Google Pixel 9a',category:'phone',price:1899,rating:4.6,tags:'كاميرا تصوير أندرويد جودة',useCases:'تصوير يومي'},
{name:'Apple iPhone 16e',category:'phone',price:2094,rating:4.4,tags:'آيفون أداء كاميرا بطارية',useCases:'تصوير أداء يومي'},
{name:'Lenovo IdeaPad 1',category:'laptop',price:1899,rating:4.3,tags:'اقتصادي دراسة اوفيس',useCases:'دراسة جامعة اوفيس'},
{name:'HP 15',category:'laptop',price:2299,rating:4.4,tags:'دراسة عمل اوفيس بطارية',useCases:'دراسة عمل جامعة'},
{name:'Acer Aspire 3',category:'laptop',price:1999,rating:4.3,tags:'اقتصادي دراسة عمل',useCases:'دراسة اوفيس'},
{name:'Lenovo IdeaPad Slim 3',category:'laptop',price:2799,rating:4.5,tags:'دراسة عمل بطارية',useCases:'جامعة عمل برمجة'},
{name:'ASUS Vivobook 15',category:'laptop',price:2999,rating:4.5,tags:'عمل دراسة شاشة بطارية',useCases:'عمل جامعة برمجة'},
{name:'HP Victus 15',category:'laptop',price:3299,rating:4.6,tags:'gaming أداء ألعاب',useCases:'ألعاب عمل'},
{name:'Lenovo LOQ 15',category:'laptop',price:3999,rating:4.7,tags:'gaming أداء قوي ألعاب',useCases:'ألعاب برمجة'},
{name:'ASUS TUF Gaming A15',category:'laptop',price:4299,rating:4.7,tags:'gaming أداء قوي ألعاب بطارية',useCases:'ألعاب احترافي'},
{name:'Samsung شاشة 24 بوصة',category:'screen',price:449,rating:4.2,tags:'اقتصادي مكتب',useCases:'عمل دراسة'},
{name:'AOC Gaming 24',category:'screen',price:599,rating:4.4,tags:'gaming ألعاب سريع',useCases:'ألعاب'},
{name:'LG شاشة 27 بوصة',category:'screen',price:799,rating:4.5,tags:'عمل دراسة شاشة كبيرة',useCases:'عمل دراسة'},
{name:'Samsung شاشة 32 بوصة',category:'screen',price:1199,rating:4.5,tags:'شاشة كبيرة ترفيه',useCases:'أفلام ألعاب'},
{name:'MSI Gaming 27',category:'screen',price:1299,rating:4.6,tags:'gaming أداء ألعاب',useCases:'ألعاب'},
{name:'LG UltraGear 27',category:'screen',price:1499,rating:4.6,tags:'gaming احترافي أداء',useCases:'ألعاب احترافي'},
{name:'Samsung Galaxy Buds FE',category:'headphones',price:299,rating:4.4,tags:'اقتصادي لاسلكي يومي',useCases:'يومي مكالمات'},
{name:'JBL Tune 770NC',category:'headphones',price:349,rating:4.5,tags:'لاسلكي عزل بطارية',useCases:'سفر يومي'},
{name:'Anker Soundcore',category:'headphones',price:399,rating:4.5,tags:'لاسلكي بطارية قيمة',useCases:'سفر يومي'},
{name:'Sony WH-CH520',category:'headphones',price:449,rating:4.6,tags:'خفيفة بطارية لاسلكي',useCases:'يومي سفر'},
{name:'Soundcore Q45',category:'headphones',price:599,rating:4.6,tags:'عزل بطارية لاسلكي',useCases:'سفر عمل'},
{name:'Sony WH-1000XM5',category:'headphones',price:1299,rating:4.7,tags:'عزل احترافي جودة',useCases:'سفر عمل'},
{name:'Samsung Galaxy Tab A9',category:'tablet',price:699,rating:4.4,tags:'اقتصادي دراسة أطفال',useCases:'دراسة أطفال ترفيه'},
{name:'Lenovo Tab M11',category:'tablet',price:899,rating:4.4,tags:'دراسة شاشة كبيرة',useCases:'دراسة أطفال'},
{name:'Xiaomi Pad 7',category:'tablet',price:1499,rating:4.5,tags:'أداء شاشة دراسة',useCases:'دراسة ترفيه'},
{name:'Samsung Galaxy Tab S9 FE',category:'tablet',price:1599,rating:4.6,tags:'دراسة أداء شاشة',useCases:'جامعة دراسة'},
{name:'iPad 11',category:'tablet',price:1699,rating:4.6,tags:'دراسة أداء تطبيقات',useCases:'دراسة جامعة عمل'},
{name:'Samsung 43 بوصة Smart TV',category:'tv',price:1199,rating:4.4,tags:'4K اقتصادي ترفيه',useCases:'أفلام ترفيه'},
{name:'Hisense 55 بوصة 4K',category:'tv',price:1399,rating:4.4,tags:'4K قيمة أفلام',useCases:'أفلام ترفيه'},
{name:'TCL 55 بوصة 4K',category:'tv',price:1599,rating:4.5,tags:'4K ألعاب ترفيه',useCases:'أفلام ألعاب'},
{name:'LG 55 بوصة 4K',category:'tv',price:1799,rating:4.5,tags:'4K جودة ترفيه',useCases:'أفلام ألعاب'},
{name:'Samsung 65 بوصة 4K',category:'tv',price:2499,rating:4.6,tags:'4K شاشة كبيرة',useCases:'أفلام ألعاب'},
{name:'Xiaomi Redmi Watch 5',category:'watch',price:399,rating:4.4,tags:'اقتصادي رياضة بطارية',useCases:'رياضة يومي'},
{name:'Amazfit Active 2',category:'watch',price:499,rating:4.5,tags:'رياضة بطارية صحة',useCases:'رياضة يومي'},
{name:'Samsung Galaxy Watch7',category:'watch',price:799,rating:4.6,tags:'رياضة جودة ذكية',useCases:'رياضة يومي'},
{name:'Apple Watch SE',category:'watch',price:999,rating:4.6,tags:'رياضة آيفون ذكية',useCases:'رياضة يومي'},
{name:'Philips Air Fryer',category:'kitchen',price:299,rating:4.5,tags:'اقتصادي طبخ',useCases:'طبخ يومي'},
{name:'Tefal قلاية هوائية',category:'kitchen',price:449,rating:4.5,tags:'طبخ جودة',useCases:'طبخ يومي'},
{name:'Black+Decker خلاط',category:'kitchen',price:199,rating:4.3,tags:'اقتصادي مطبخ',useCases:'طبخ يومي'},
{name:'قدر ضغط كهربائي',category:'kitchen',price:299,rating:4.3,tags:'طبخ اقتصادي',useCases:'طبخ يومي'},
{name:'Philips ماكينة قهوة',category:'kitchen',price:399,rating:4.4,tags:'قهوة مطبخ',useCases:'قهوة يومي'},
{name:'Ninja Air Fryer',category:'kitchen',price:599,rating:4.6,tags:'طبخ أداء جودة',useCases:'طبخ يومي'},
{name:'مكواة بخار Philips',category:'home',price:249,rating:4.4,tags:'منزل اقتصادي',useCases:'منزل يومي'},
{name:'مكنسة Black+Decker',category:'home',price:399,rating:4.3,tags:'تنظيف اقتصادي',useCases:'منزل تنظيف'},
{name:'منقي هواء Xiaomi',category:'home',price:549,rating:4.5,tags:'منزل هواء',useCases:'منزل'},
{name:'مكنسة Xiaomi لاسلكية',category:'home',price:699,rating:4.5,tags:'لاسلكي تنظيف',useCases:'منزل تنظيف'},
{name:'Xiaomi Robot Vacuum',category:'home',price:899,rating:4.4,tags:'روبوت تنظيف ذكي',useCases:'منزل تنظيف'},
{name:'منظم سيارة',category:'car',price:79,rating:4.2,tags:'اقتصادي سيارة',useCases:'سيارة'},
{name:'شاحن سيارة Anker',category:'car',price:99,rating:4.5,tags:'سيارة شحن',useCases:'سيارة'},
{name:'مكنسة سيارة لاسلكية',category:'car',price:129,rating:4.3,tags:'تنظيف سيارة لاسلكي',useCases:'سيارة تنظيف'},
{name:'منفاخ إطارات محمول',category:'car',price:169,rating:4.4,tags:'سيارة طوارئ',useCases:'سيارة سفر'},
{name:'كاميرا سيارة 70mai',category:'car',price:299,rating:4.5,tags:'سيارة كاميرا تسجيل',useCases:'سيارة سفر'},
{name:'يد تحكم Xbox',category:'gaming',price:249,rating:4.6,tags:'gaming xbox ألعاب',useCases:'ألعاب'},
{name:'سماعة ألعاب HyperX',category:'gaming',price:299,rating:4.5,tags:'gaming سماعة صوت',useCases:'ألعاب'},
{name:'يد تحكم PS5 DualSense',category:'gaming',price:299,rating:4.7,tags:'gaming بلايستيشن',useCases:'ألعاب'},
{name:'كرسي ألعاب',category:'gaming',price:599,rating:4.5,tags:'gaming راحة',useCases:'ألعاب'},
{name:'Nintendo Switch OLED',category:'gaming',price:1399,rating:4.7,tags:'gaming محمول',useCases:'ألعاب سفر'},
{name:'PlayStation 5 Slim',category:'gaming',price:1999,rating:4.8,tags:'gaming بلايستيشن أداء',useCases:'ألعاب'},
{name:'ماكينة حلاقة Philips',category:'beauty',price:199,rating:4.4,tags:'حلاقة اقتصادي',useCases:'حلاقة يومي'},
{name:'مجفف شعر Remington',category:'beauty',price:179,rating:4.3,tags:'شعر اقتصادي',useCases:'شعر'},
{name:'ماكينة تشذيب Braun',category:'beauty',price:249,rating:4.4,tags:'حلاقة تشذيب',useCases:'حلاقة'},
{name:'فرشاة أسنان كهربائية Oral-B',category:'beauty',price:299,rating:4.5,tags:'أسنان عناية',useCases:'عناية يومية'},
{name:'لعبة تعليمية للأطفال',category:'kids',price:89,rating:4.4,tags:'أطفال تعليم اقتصادي',useCases:'تعليم أطفال'},
{name:'حقيبة مدرسية أطفال',category:'kids',price:129,rating:4.3,tags:'أطفال مدرسة',useCases:'مدرسة'},
{name:'سكوتر أطفال',category:'kids',price:199,rating:4.4,tags:'أطفال حركة',useCases:'أطفال'},
{name:'طاولة دراسة أطفال',category:'kids',price:299,rating:4.4,tags:'أطفال دراسة',useCases:'دراسة'},
{name:'كرسي سيارة للأطفال',category:'kids',price:349,rating:4.6,tags:'أطفال سيارة أمان',useCases:'سيارة أطفال'},
{name:'حبل قفز رياضي',category:'sport',price:59,rating:4.3,tags:'رياضة اقتصادي',useCases:'رياضة'},
{name:'حصيرة تمارين',category:'sport',price:99,rating:4.4,tags:'رياضة منزل',useCases:'رياضة منزل'},
{name:'دمبل قابل للتعديل',category:'sport',price:399,rating:4.5,tags:'رياضة قوة',useCases:'رياضة منزل'},
{name:'بنش تمارين',category:'sport',price:499,rating:4.4,tags:'رياضة قوة',useCases:'رياضة منزل'},
{name:'دراجة ثابتة',category:'sport',price:799,rating:4.5,tags:'رياضة كارديو',useCases:'رياضة منزل'},
{name:'منظم حقائب سفر',category:'travel',price:79,rating:4.3,tags:'سفر اقتصادي تنظيم',useCases:'سفر'},
{name:'حقيبة ظهر للسفر',category:'travel',price:179,rating:4.5,tags:'سفر حقيبة',useCases:'سفر'},
{name:'شنطة سفر متوسطة',category:'travel',price:249,rating:4.4,tags:'سفر حقيبة',useCases:'سفر'},
{name:'شنطة سفر كبيرة',category:'travel',price:329,rating:4.5,tags:'سفر كبيرة',useCases:'سفر'},
{name:'شنطة لابتوب',category:'travel',price:149,rating:4.4,tags:'سفر لابتوب عمل',useCases:'عمل سفر'},
{name:'كاميرا مراقبة منزلية',category:'camera',price:199,rating:4.4,tags:'كاميرا منزل أمان',useCases:'منزل أمان'},
{name:'Canon EOS 2000D',category:'camera',price:1899,rating:4.5,tags:'camera تصوير صور',useCases:'تصوير'},
{name:'Canon EOS R50',category:'camera',price:2499,rating:4.7,tags:'camera تصوير فيديو',useCases:'تصوير فيديو'},
{name:'Sony ZV-E10',category:'camera',price:2699,rating:4.7,tags:'camera تصوير فيديو محتوى',useCases:'تصوير فيديو محتوى'},
{name:'DJI Osmo Pocket 3',category:'camera',price:1999,rating:4.8,tags:'camera تصوير فيديو محمول',useCases:'تصوير فيديو سفر'}
];