// أسعار ومنتجات مرصودة حديثًا من السوق السعودي — للتحديث الدوري فقط
window.DABBIRHA_LIVE_PRODUCTS=[
{name:'Samsung Galaxy S26 Ultra 256GB',category:'phone',price:3939,rating:4.7,tags:'فلاجشيب كاميرا أداء بطارية',useCases:'ألعاب تصوير احترافي'},
{name:'Samsung Galaxy S26 256GB',category:'phone',price:3009,rating:4.7,tags:'فلاجشيب أداء كاميرا',useCases:'ألعاب تصوير يومي'},
{name:'Samsung Galaxy S25 Ultra 256GB',category:'phone',price:3259,rating:4.7,tags:'فلاجشيب كاميرا أداء',useCases:'ألعاب تصوير احترافي'},
{name:'Samsung Galaxy A57 5G 8GB 256GB',category:'phone',price:1509,rating:4.4,tags:'5G قيمة بطارية كاميرا',useCases:'يومي تصوير ألعاب خفيفة'},
{name:'Samsung Galaxy A36 5G 6GB 128GB',category:'phone',price:909,rating:4.4,tags:'5G قيمة بطارية كاميرا',useCases:'يومي تصوير ألعاب خفيفة'},
{name:'Samsung Galaxy Z Fold 7 256GB',category:'phone',price:5259,rating:4.6,tags:'قابل للطي فخم أداء',useCases:'عمل إنتاجية احترافي'},
{name:'Motorola Edge 60 Stylus 5G 8GB 256GB',category:'phone',price:849,rating:4.2,tags:'5G قلم قيمة',useCases:'يومي دراسة عمل'},
{name:'Samsung Galaxy Buds3 Pro',category:'headphones',price:539,rating:4.5,tags:'عزل لاسلكي احترافي',useCases:'سفر عمل مكالمات'},
{name:'JBL Tune 770NC',category:'headphones',price:299,rating:4.1,tags:'عزل لاسلكي بطارية باس',useCases:'سفر عمل موسيقى'},
{name:'Apple EarPods USB-C',category:'headphones',price:89,rating:4.3,tags:'سلكية اقتصادي آيفون',useCases:'يومي مكالمات'},
{name:'Huawei FreeBuds SE 2',category:'headphones',price:76,rating:4.3,tags:'لاسلكي اقتصادي بطارية',useCases:'يومي مكالمات'},
{name:'Soundcore P20i',category:'headphones',price:69,rating:4.4,tags:'لاسلكي اقتصادي باس',useCases:'يومي رياضة'},
{name:'Samsung Galaxy Watch8 44mm',category:'watch',price:909,rating:4.5,tags:'ساعة ذكية رياضة GPS',useCases:'رياضة يومي'},
{name:'Samsung Galaxy Fit3',category:'watch',price:139,rating:4.6,tags:'اقتصادي رياضة بطارية',useCases:'رياضة يومي'},
{name:'Samsung Galaxy SmartTag2',category:'home',price:89,rating:4.5,tags:'تتبع ذكي',useCases:'منزل سفر'},
{name:'Samsung 25W Super Fast Charger',category:'car',price:54,rating:4.7,tags:'شاحن سريع',useCases:'جوال سيارة سفر'},
{name:'Lenovo LOQ Ryzen 5 RTX 3050 16GB 512GB',category:'laptop',price:3349,rating:4.1,tags:'gaming أداء RTX',useCases:'ألعاب برمجة'},
{name:'Lenovo LOQ Ryzen 7 RTX 5060 16GB 1TB',category:'laptop',price:4859,rating:4.7,tags:'gaming احترافي RTX',useCases:'ألعاب برمجة احترافي'},
{name:'Huawei MateBook D16 i5 16GB 1TB',category:'laptop',price:2459,rating:4.1,tags:'عمل دراسة شاشة كبيرة',useCases:'عمل جامعة'},
{name:'Dell Pro 15 Core 3 8GB 512GB',category:'laptop',price:1799,rating:4.0,tags:'اقتصادي عمل',useCases:'عمل دراسة'},
{name:'Lenovo IdeaPad Slim 3 Ryzen 5 8GB 512GB',category:'laptop',price:1899,rating:4.0,tags:'اقتصادي دراسة عمل',useCases:'دراسة جامعة عمل'},
{name:'MacBook Neo A18 Pro 8GB 256GB',category:'laptop',price:3199,rating:4.7,tags:'ابل خفيف عمل دراسة',useCases:'عمل جامعة دراسة'},
{name:'ASUS Vivobook S14 Ryzen AI 7 16GB 512GB',category:'laptop',price:3109,rating:5.0,tags:'عمل دراسة أداء',useCases:'عمل جامعة برمجة'},
{name:'Lenovo Yoga 7 OLED 16GB 1TB',category:'laptop',price:4799,rating:4.8,tags:'OLED 2in1 عمل',useCases:'عمل جامعة برمجة'},
{name:'HP OmniBook 5 Core 5 16GB 512GB',category:'laptop',price:4299,rating:4.5,tags:'عمل دراسة',useCases:'عمل جامعة'},
{name:'TCL MEGABOOK K15S i5 16GB 512GB',category:'laptop',price:1999,rating:4.2,tags:'اقتصادي أداء دراسة',useCases:'عمل جامعة'},
{name:'ASUS Zenbook A14 Snapdragon X Elite 32GB 1TB',category:'laptop',price:4999,rating:5.0,tags:'خفيف بطارية عمل',useCases:'عمل جامعة'},
{name:'iPad 2025 A16 128GB',category:'tablet',price:1889,rating:4.6,tags:'ابل دراسة أداء',useCases:'دراسة جامعة عمل'},
{name:'Honor Pad 10 8GB 256GB',category:'tablet',price:1322,rating:4.5,tags:'شاشة كبيرة دراسة قيمة',useCases:'دراسة ترفيه'},
{name:'Xiaomi Pad 7',category:'tablet',price:1499,rating:4.5,tags:'أداء شاشة دراسة',useCases:'دراسة ترفيه'},
{name:'Samsung Galaxy Tab S9 FE',category:'tablet',price:1599,rating:4.6,tags:'دراسة أداء شاشة',useCases:'جامعة دراسة'},
{name:'EZVIZ TY2 Smart Camera',category:'camera',price:69,rating:4.4,tags:'كاميرا منزلية ذكية',useCases:'منزل مراقبة'},
{name:'EZVIZ C6N Smart 2K Camera',category:'camera',price:75,rating:4.4,tags:'كاميرا منزلية 2K',useCases:'منزل مراقبة'},
{name:'Samsung Galaxy A16 4GB 128GB',category:'phone',price:599,rating:4.4,tags:'اقتصادي بطارية',useCases:'يومي دراسة'},
{name:'Apple iPhone 15 128GB',category:'phone',price:2749,rating:4.6,tags:'آيفون كاميرا أداء',useCases:'تصوير يومي'}
];
(function(){window.DABBIRHA_PRODUCTS=(window.DABBIRHA_PRODUCTS||[]).concat(window.DABBIRHA_LIVE_PRODUCTS||[]);})();
